# Generated by Django 3.1.5 on 2021-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authenticationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationrequest',
            name='code',
            field=models.CharField(default='8U7k4t3V6P2I2y2D0z3h9g2p2e9A0d7M5r0L9J4e0P1u5j7l1I9x9h0f1l6O', max_length=30, unique=True),
        ),
    ]
