# Generated by Django 3.1.5 on 2021-02-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210205_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('code', models.CharField(default='4w4l1C5r0J6T3j8E0p3s8g1C9d9c3X8u3K0B0F3O8W0v9U2V6P6F8Q0Q4G4Y', max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthenticationRequest',
        ),
        migrations.RemoveField(
            model_name='requesttoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='requesttoken',
            name='code',
            field=models.CharField(default='9e0U1B4S4C3o2E0w8w3g4c6T3e0z3P5z4D8O9G9a5c1v9o6V2O9z9i5W2S9X', max_length=30, unique=True),
        ),
    ]
