# Generated by Django 3.1.5 on 2021-02-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210205_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='code',
            field=models.CharField(default='8T7w6A7T8C1l7U1T8X9p9Q1e7U0p1o5S0Q1M6d1G2q1d4O4v2F6h0V0t0y0d', max_length=30),
        ),
        migrations.AlterField(
            model_name='requesttoken',
            name='code',
            field=models.CharField(default='1C5e8n7g9B4w9B1X0H5f3j0C4a2D4b1Y3M6l1Q8f0i0A5q1t1e7t1P5T1s1q', max_length=30),
        ),
    ]
